// <auto-generated />
using System;
using ForumDyskusyjne.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForumDyskusyjne.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20251117172153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForumDyskusyjne.Models.AdminAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("admin_actions", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer")
                        .HasColumnName("download_count");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFilename")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_filename");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("attachment", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.BannedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_type");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity_level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("banned_word", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.ContentModerationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_taken");

                    b.Property<int?>("BannedWordId")
                        .HasColumnType("integer")
                        .HasColumnName("banned_word_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectedText")
                        .HasColumnType("text")
                        .HasColumnName("detected_text");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BannedWordId");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("content_moderation_logs", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Forum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("forum", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.ForumModerator", b =>
                {
                    b.Property<int>("ForumId")
                        .HasColumnType("integer")
                        .HasColumnName("forum_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_by");

                    b.HasKey("ForumId", "UserId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("UserId");

                    b.ToTable("forum_moderator", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.ForumPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowAnonymousPost")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_anonymous_post");

                    b.Property<bool>("AllowAnonymousView")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_anonymous_view");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean")
                        .HasColumnName("can_read");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("boolean")
                        .HasColumnName("can_write");

                    b.Property<int>("ForumId")
                        .HasColumnType("integer")
                        .HasColumnName("forum_id");

                    b.HasKey("Id");

                    b.HasIndex("ForumId");

                    b.ToTable("forum_permission", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<int>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ThreadId");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.PrivateMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("DeletedByRecipient")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted_by_recipient");

                    b.Property<bool>("DeletedBySender")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted_by_sender");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("private_messages", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text")
                        .HasColumnName("admin_notes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at");

                    b.Property<int?>("HandledBy")
                        .HasColumnType("integer")
                        .HasColumnName("handled_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("ReportedMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("reported_message_id");

                    b.Property<int>("ReporterId")
                        .HasColumnType("integer")
                        .HasColumnName("reporter_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("HandledBy");

                    b.HasIndex("ReportedMessageId");

                    b.HasIndex("ReporterId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Thread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ForumId")
                        .HasColumnType("integer")
                        .HasColumnName("forum_id");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<int>("RepliesCount")
                        .HasColumnType("integer")
                        .HasColumnName("replies_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Views")
                        .HasColumnType("integer")
                        .HasColumnName("views");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ForumId");

                    b.ToTable("thread", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoLogoutMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("auto_logout_minutes");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("BanExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ban_expires_at");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentRankId")
                        .HasColumnType("integer")
                        .HasColumnName("current_rank_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_ip_address");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("login_attempts");

                    b.Property<int>("MessagesPerPage")
                        .HasColumnType("integer")
                        .HasColumnName("messages_per_page");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("PostCount")
                        .HasColumnType("integer")
                        .HasColumnName("post_count");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("ThreadsPerPage")
                        .HasColumnType("integer")
                        .HasColumnName("threads_per_page");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRankId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.UserRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanBeSetManually")
                        .HasColumnType("boolean")
                        .HasColumnName("can_be_set_manually");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxMessages")
                        .HasColumnType("integer")
                        .HasColumnName("max_messages");

                    b.Property<int>("MinMessages")
                        .HasColumnType("integer")
                        .HasColumnName("min_messages");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("user_rank", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.UserRankHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_reason");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("NewRankId")
                        .HasColumnType("integer")
                        .HasColumnName("new_rank_id");

                    b.Property<int?>("OldRankId")
                        .HasColumnType("integer")
                        .HasColumnName("old_rank_id");

                    b.Property<int?>("PostCountAtChange")
                        .HasColumnType("integer")
                        .HasColumnName("post_count_at_change");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("NewRankId");

                    b.HasIndex("OldRankId");

                    b.HasIndex("UserId");

                    b.ToTable("user_rank_history", (string)null);
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.AdminAction", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.User", "Admin")
                        .WithMany("AdminActions")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Announcement", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.User", "CreatedByUser")
                        .WithMany("Announcements")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Attachment", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.BannedWord", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.User", "CreatedByUser")
                        .WithMany("BannedWords")
                        .HasForeignKey("CreatedBy");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.ContentModerationLog", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.BannedWord", "BannedWord")
                        .WithMany("ContentModerationLogs")
                        .HasForeignKey("BannedWordId");

                    b.HasOne("ForumDyskusyjne.Models.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId");

                    b.HasOne("ForumDyskusyjne.Models.User", "User")
                        .WithMany("ContentModerationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannedWord");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Forum", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.Category", "Category")
                        .WithMany("Forums")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.ForumModerator", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ForumDyskusyjne.Models.Forum", "Forum")
                        .WithMany("ForumModerators")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumDyskusyjne.Models.User", "User")
                        .WithMany("ModeratedForums")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Forum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.ForumPermission", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.Forum", "Forum")
                        .WithMany("ForumPermissions")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forum");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Message", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.User", "Author")
                        .WithMany("Messages")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumDyskusyjne.Models.Thread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.PasswordResetToken", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.PrivateMessage", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.User", "Recipient")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForumDyskusyjne.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Report", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.User", "HandledByUser")
                        .WithMany("HandledReports")
                        .HasForeignKey("HandledBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ForumDyskusyjne.Models.Message", "ReportedMessage")
                        .WithMany("Reports")
                        .HasForeignKey("ReportedMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumDyskusyjne.Models.User", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HandledByUser");

                    b.Navigation("ReportedMessage");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Thread", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.User", "Author")
                        .WithMany("Threads")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumDyskusyjne.Models.Forum", "Forum")
                        .WithMany("Threads")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Forum");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.User", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.UserRank", "CurrentRank")
                        .WithMany("Users")
                        .HasForeignKey("CurrentRankId");

                    b.Navigation("CurrentRank");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.UserRankHistory", b =>
                {
                    b.HasOne("ForumDyskusyjne.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ForumDyskusyjne.Models.UserRank", "NewRank")
                        .WithMany("RankHistories")
                        .HasForeignKey("NewRankId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ForumDyskusyjne.Models.UserRank", "OldRank")
                        .WithMany()
                        .HasForeignKey("OldRankId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ForumDyskusyjne.Models.User", "User")
                        .WithMany("RankHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("NewRank");

                    b.Navigation("OldRank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.BannedWord", b =>
                {
                    b.Navigation("ContentModerationLogs");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Category", b =>
                {
                    b.Navigation("Forums");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Forum", b =>
                {
                    b.Navigation("ForumModerators");

                    b.Navigation("ForumPermissions");

                    b.Navigation("Threads");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Message", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.Thread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.User", b =>
                {
                    b.Navigation("AdminActions");

                    b.Navigation("Announcements");

                    b.Navigation("BannedWords");

                    b.Navigation("ContentModerationLogs");

                    b.Navigation("HandledReports");

                    b.Navigation("Messages");

                    b.Navigation("ModeratedForums");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RankHistory");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("Reports");

                    b.Navigation("SentMessages");

                    b.Navigation("Threads");
                });

            modelBuilder.Entity("ForumDyskusyjne.Models.UserRank", b =>
                {
                    b.Navigation("RankHistories");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
